spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/demo_client
        username: root
        password: root
        hikari.maxLifetime: 1765000
        hikari.maximumPoolSize: 15

mybatis:
    mapper-locations: classpath:mybatis/*.xml
    type-aliases-package: com.glitter.spring.boot.bean
    configuration:
        # 这里的配置与mybatis-config.xml的settings属性配置时一一对应的,不同点是这里属性名要换成中划线
        cache-enabled: false
        lazy-loading-enabled: false
        aggressive-lazy-loading: false
        multiple-result-sets-enabled: true
        use-column-label: true
        use-generated-keys: true
        auto-mapping-behavior: FULL
        default-statement-timeout: 25000
        default-fetch-size: 100
        map-underscore-to-camel-case: true

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql