server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: true
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: true
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://peer2:8762/eureka/
